/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ludii_cpp_ai_LudiiKriegspielCppAI */

#ifndef _Included_ludii_cpp_ai_LudiiKriegspielCppAI
#define _Included_ludii_cpp_ai_LudiiKriegspielCppAI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ludii_cpp_ai_LudiiKriegspielCppAI
 * Method:    nativeSelectAction
 * Signature: (Lgame/Game;Lother/context/Context;DIILjava/lang/String;Ljava/lang/String;)Lother/move/Move;
 */
JNIEXPORT jobject JNICALL Java_ludii_1cpp_1ai_LudiiKriegspielCppAI_nativeSelectAction
  (JNIEnv *, jobject, jobject, jobject, jdouble, jint, jint, jstring, jstring);

/*
 * Class:     ludii_cpp_ai_LudiiKriegspielCppAI
 * Method:    nativeInitAI
 * Signature: (Lgame/Game;I)V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiKriegspielCppAI_nativeInitAI
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     ludii_cpp_ai_LudiiKriegspielCppAI
 * Method:    nativeCloseAI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiKriegspielCppAI_nativeCloseAI
  (JNIEnv *, jobject);

/*
 * Class:     ludii_cpp_ai_LudiiKriegspielCppAI
 * Method:    nativeSupportsGame
 * Signature: (Lgame/Game;)Z
 */
JNIEXPORT jboolean JNICALL Java_ludii_1cpp_1ai_LudiiKriegspielCppAI_nativeSupportsGame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ludii_cpp_ai_LudiiKriegspielCppAI
 * Method:    nativeStaticInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiKriegspielCppAI_nativeStaticInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
